import XCTest
@testable import ScaleKit

/// Golden vectors generated by `analysis/tools/golden_gen.py` — an independent
/// Python port of the decompiled Lifesense codec (the truth model).
final class GoldenVectorTests: XCTestCase {

    static let vectors: [String: Any] = {
        let url = Bundle.module.url(forResource: "golden_vectors", withExtension: "json")!
        return try! JSONSerialization.jsonObject(with: Data(contentsOf: url)) as! [String: Any]
    }()

    static let MAC = "31:06:1B:CB:0B:D8"   // captured live from the scale 2026-09-20

    // MARK: - CRC32

    func testCRC32GoldenVectors() {
        let vec = Self.vectors["crc32"] as! [String: [String]]
        let cases: [[UInt8]] = [[UInt8](), Array("123456789".utf8), Array(hex: "31061BCB0BD8"), [UInt8](repeating: 0x11, count: 18)]
        let keys = ["empty", "123456789", "mac_payload", "ones_18"]
        for (key, data) in zip(keys, cases) {
            XCTAssertEqual(CRC32.checksumString(data), vec[key]![0], "CRC32 mismatch for \(key)")
            XCTAssertEqual(CRC32.checksumString(data), vec[key]![1], "CRC32 self mismatch for \(key)")
        }
        // Standard-check difference vs zlib documented:
        XCTAssertNotEqual(CRC32.checksumString(Array("123456789".utf8)), "CBF43926",
                          "must NOT be zlib CRC32 (init 0 variant confirmed)")
    }

    // MARK: - XOR obfuscation

    func testXorGoldenVectors() {
        let vec = Self.vectors["xor"] as! [String: String]
        let key = A6Obfuscation.macBytes(Self.MAC)
        XCTAssertEqual(A6Obfuscation.xor(A6Hex.decode("0007AABBCCDDEEFF0011"), key: key).hex,
                       vec["cmd_0007_challenge"])
        XCTAssertEqual(A6Obfuscation.xor(A6Hex.decode("10010001603c001600000000ffff"), key: key).hex,
                       vec["cmd_1001_userinfo"])
    }

    // MARK: - ACK packets

    func testAckGoldenVectors() {
        let vec = Self.vectors["ack"] as! [String: String]
        XCTAssertEqual(A6Commands.ack(ok: true, mac: Self.MAC, xored: true).hex, vec["ok_xored"])
        XCTAssertEqual(A6Commands.ack(ok: false, mac: Self.MAC, xored: true).hex, vec["fail_xored"])
        XCTAssertEqual(A6Commands.ack(ok: true, mac: Self.MAC, xored: false).hex, vec["ok_plain"])
    }

    // MARK: - Device ID derivation

    func testDeviceIdGoldenVector() {
        let vec = Self.vectors["deviceId"] as! [String: String]
        XCTAssertEqual(A6Commands.deviceId(verificationCodeHex6: vec["code"]!, mac: vec["mac"]!),
                       vec["deviceId"])
    }

    // MARK: - Frame encoding (app → device)

    func testEncodeGoldenVectors() {
        let vec = Self.vectors["encode"] as! [String: [String: String]]
        let codec = A6FrameCodec()

        // register 0x0001 (9-byte payload → 1 frame, XORed)
        let reg = A6Commands.register(deviceIdHex12: "31061BCB0BD8", state: .normalUnregister, mac: Self.MAC)
        XCTAssertEqual(reg.hex, vec["register_cmd"]!["input_hex"])
        XCTAssertEqual(codec.encodePacket(payload: reg, mac: Self.MAC, xored: true).hex,
                       vec["register_cmd"]!["frames_hex"])

        // register plain variant (fw < 1.4.0.25)
        XCTAssertEqual(codec.encodePacket(payload: reg, mac: Self.MAC, xored: false).hex,
                       vec["register_cmd_plain"]!["frames_hex"])

        // auth response 0x0008 (ASCII-hex field quirk)
        let auth = A6Commands.authResponse(success: true, verificationCodeHex6: "AABBCCDDEEFF", mode: 1)
        XCTAssertEqual(auth.hex, vec["auth_response"]!["input_hex"])
        XCTAssertEqual(codec.encodePacket(payload: auth, mac: Self.MAC, xored: true).hex,
                       vec["auth_response"]!["frames_hex"])

        // user info push 0x1001
        let ui = A6Commands.pushUserInfo(slot: 0, sexMale: true, age: 33, heightMeters: 1.75,
                                         athlete: false, activityLevel: 0, weightKg: nil)
        XCTAssertEqual(ui.hex, vec["user_info"]!["input_hex"])
        XCTAssertEqual(codec.encodePacket(payload: ui, mac: Self.MAC, xored: true).hex,
                       vec["user_info"]!["frames_hex"])

        // 24-byte payload → 2 frames + CRC32
        let big = (0..<24).map { UInt8($0) }
        XCTAssertEqual(codec.encodePacket(payload: big, mac: Self.MAC, xored: true).hex,
                       vec["big_24b_2frames"]!["frames_hex"])
    }

    // MARK: - Frame decoding (device → app)

    func testDecodeAuthChallengeGoldenVector() throws {
        let vec = (Self.vectors["decode"] as! [String: [String: String]])["auth_challenge"]!
        let codec = A6FrameCodec()
        let frame = try XCTUnwrap(codec.decodeFrame(A6Hex.decode(vec["wire_hex"]!),
                                                    mac: vec["mac"]!,
                                                    xored: true))
        XCTAssertEqual(frame.commandHex, vec["expect_command"])
        XCTAssertEqual(frame.payload.hex, vec["expect_payload_hex"])
        XCTAssertEqual(frame.count, 1)
        XCTAssertEqual(frame.serial, 0)

        // full packet assembly path (device→app: plaintext CRC policy)
        var assembler = A6FrameCodec.PacketAssembler(mac: vec["mac"]!, xored: true,
                                                     crcPolicy: .overPlaintext)
        let result = assembler.ingest(frame)
        guard case .success(let payload)? = result else { return XCTFail("assembly failed") }
        XCTAssertEqual(payload.hex, vec["expect_payload_hex"])
    }

    // MARK: - Weight record parsing

    func testWeightRecordGoldenVector() {
        let vec = Self.vectors["weight_record"] as! [String: Any]
        let parsed = vec["parsed"] as! [String: Any]
        let record = A6WeightRecordParser.parse(A6Hex.decode(vec["full_payload_hex"] as! String))

        let rec = try! XCTUnwrap(record)
        XCTAssertEqual(rec.remainCount, parsed["remainCount"] as! Int)
        XCTAssertEqual(rec.unitRaw, parsed["unit"] as! Int)
        XCTAssertEqual(rec.weightKg, (parsed["weightKg"] as! Double), accuracy: 0.0001)
        XCTAssertEqual(rec.utc ?? -1, parsed["utc"] as! Int)
        XCTAssertEqual(rec.impedanceOhm ?? -1, parsed["impedance"] as! Int)
    }

    func testWeightRecordMinimal() {
        // flags = 0 → only weight, no optional fields
        var p = A6Hex.decode("4802")
        p += A6Bytes.from(short: 0)          // remain
        p += A6Bytes.from(int: 0)            // flags: unit kg, nothing present
        p += A6Bytes.from(short: 6500)       // 65.00 kg
        let r = A6WeightRecordParser.parse(p)
        XCTAssertNotNil(r)
        XCTAssertEqual(r?.weightKg ?? 0, 65.00, accuracy: 0.0001)
        XCTAssertNil(r?.impedanceOhm)
        XCTAssertNil(r?.utc)
    }

    // MARK: - Security gate

    func testXorVariantGate() {
        XCTAssertTrue(A6Security.isXorVariant(firmwareVersion: "1.4.0.25"))   // equal → on
        XCTAssertTrue(A6Security.isXorVariant(firmwareVersion: "1.5.0.0"))    // newer → on
        XCTAssertTrue(A6Security.isXorVariant(firmwareVersion: "1.4.0.251"))  // Java prefix rule → on
        XCTAssertFalse(A6Security.isXorVariant(firmwareVersion: "1.3.0.0"))   // older → off
        XCTAssertFalse(A6Security.isXorVariant(firmwareVersion: "1.4.0.2"))   // lexicographic < gate
    }

    // MARK: - Round-trip tests (per real direction)

    /// app→device: ALL scale commands are ≤18 bytes → single frame → no CRC.
    /// Encode → frame-split → decode → assemble must return the original payload.
    func testAppToDeviceRoundTrip() {
        let codec = A6FrameCodec()
        let mac = Self.MAC
        for payload in [A6Hex.decode("000131061BCB0BD801"),
                        A6Hex.decode("100100002100AF0000FFFF"),
                        (0..<18).map { UInt8($0) }] {          // max single-frame payload
            for xored in [true, false] {
                let wire = codec.encodePacket(payload: payload, mac: mac, xored: xored)
                var assembler = A6FrameCodec.PacketAssembler(mac: mac, xored: xored)
                var offset = 0
                var result: Result<[UInt8], A6Error>?
                while offset < wire.count {
                    let len = Int(wire[offset + 1])
                    let frame = codec.decodeFrame(Array(wire[offset..<(offset + 2 + len)]),
                                                  mac: mac, xored: xored)
                    result = assembler.ingest(try! XCTUnwrap(frame))
                    offset += 2 + len
                }
                guard case .success(let decoded)? = result else { return XCTFail("round trip failed") }
                XCTAssertEqual(decoded, payload)
            }
        }
    }

    /// device→app multi-frame: the FIRMWARE transmits `xor(plaintext ‖ crc32(plaintext))`
    /// chunked into 18-byte frames (decompiled `verify()` XOR-decodes everything, then
    /// checks the trailing 4 bytes as CRC of the plaintext body).
    /// Simulate that wire format, then decode + assemble must succeed.
    func testDeviceToAppMultiFrameRoundTrip() {
        let codec = A6FrameCodec()
        let mac = Self.MAC
        let macb = A6Obfuscation.macBytes(mac)
        let payload = (0..<40).map { UInt8($0) }            // 3 frames after CRC append
        // firmware-style encode: XOR(plaintext ‖ CRC32(plaintext)), then chunk
        let full = payload + CRC32.checksumBytes(payload)
        let xoredFull = A6Obfuscation.xor(full, key: macb)
        var wire: [UInt8] = []
        var chunks: [[UInt8]] = []
        var i = 0
        while i < xoredFull.count {
            chunks.append(Array(xoredFull[i..<min(i + 18, xoredFull.count)]))
            i += 18
        }
        for (serial, chunk) in chunks.enumerated() {
            wire.append(UInt8((chunks.count << 4) | serial))
            wire.append(UInt8(chunk.count))
            wire += chunk
        }
        // decode + assemble (device→app policy)
        var assembler = A6FrameCodec.PacketAssembler(mac: mac, xored: true, crcPolicy: .overPlaintext)
        var offset = 0
        var result: Result<[UInt8], A6Error>?
        while offset < wire.count {
            let len = Int(wire[offset + 1])
            let frame = codec.decodeFrame(Array(wire[offset..<(offset + 2 + len)]), mac: mac, xored: true)
            result = assembler.ingest(try! XCTUnwrap(frame))
            offset += 2 + len
        }
        guard case .success(let decoded)? = result else { return XCTFail("device→app assembly failed") }
        XCTAssertEqual(decoded, payload)
    }

    /// Corrupted wire CRC must be rejected (integrity check works).
    func testDeviceToAppCRCRejection() {
        let codec = A6FrameCodec()
        let mac = Self.MAC
        let macb = A6Obfuscation.macBytes(mac)
        let payload = (0..<24).map { UInt8($0) }
        var full = payload + CRC32.checksumBytes(payload)
        full[10] ^= 0xFF                                     // corrupt a plaintext byte's wire form
        let xoredFull = A6Obfuscation.xor(full, key: macb)
        var wire: [UInt8] = []
        let chunk0 = Array(xoredFull[0..<18]), chunk1 = Array(xoredFull[18...])
        for (serial, chunk) in [chunk0, chunk1].enumerated() {
            wire.append(UInt8((2 << 4) | serial)); wire.append(UInt8(chunk.count)); wire += chunk
        }
        var assembler = A6FrameCodec.PacketAssembler(mac: mac, xored: true, crcPolicy: .overPlaintext)
        var result: Result<[UInt8], A6Error>?
        var offset = 0
        while offset < wire.count {
            let len = Int(wire[offset + 1])
            result = assembler.ingest(try! XCTUnwrap(codec.decodeFrame(Array(wire[offset..<(offset + 2 + len)]), mac: mac, xored: true)))
            offset += 2 + len
        }
        guard case .failure(.crcMismatch)? = result else { return XCTFail("expected crcMismatch") }
    }
}

// MARK: - Small helpers used by tests

private extension Array where Element == UInt8 {
    init(hex string: String) { self = A6Hex.decode(string) }
    var hex: String { A6Hex.encode(self) }
}

private extension UInt8 {
    init(_ v: Int) { self = UInt8(clamping: v) }
}
